import type { Metadata } from 'next';
import { Poetsen_One, Geist_Mono } from 'next/font/google';
import './globals.css';

const poetsenOne = Poetsen_One({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-poetsen-one',
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poetsenOne.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
